export const Screen = {
  HomeScreen: 'HomeScreen',
  Notification: 'Notification',
  OfferScreen: 'OfferScreen',
  NotificationOffer: 'NotificationOffer',
  NotificationFeed: 'NotificationFeed',
  NotificationActivity: 'NotificationActivity',
  ProductDetail: 'ProductDetail',
  Favorite: 'Favorite',
  WriteReview: 'WriteReview',
  SubperSale: 'SubperSale',
  Explore: 'Explore',
  SearchScreen: 'SearchScreen',
  CartScreen: 'CartScreen',
  SearchResult: 'SearchResult',
  Category: 'Category',
  SortByScreen: 'SortByScreen',
  ShipTo: 'ShipTo',
  Payment: 'Payment',
  Credit: 'Credit',
  AddCard: 'AddCard',
  Address: 'Address',
  DeleteAddress: 'DeleteAddress',
  AccountScreen: 'AccountScreen',
  Profile: 'Profile',
  ChangeName: 'ChangeName',
  Gender: 'Gender',
  BirthDay: 'BirthDay',
  Email: 'Email',
  Phone: 'Phone',
  ChangePass: 'ChangePass',
  Order: 'Order',
  SplashScreen: 'SplashScreen',
  Login: 'Login',
  Register: 'Register',
}

export const Label = {
  Save: 'Save',
}
